In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {'height': [151, 174, 138, 186,128, 136, 179, 163, 152, 131], 'Age': [63, 81, 56, 91, 47, 57, 76, 72, 62, 48]}
df = pd.DataFrame(data)
print(df)

#IF DATASET IS GIVEN
#df=pd.read_csv("Dataset.csv")


   height  Age
0     151   63
1     174   81
2     138   56
3     186   91
4     128   47
5     136   57
6     179   76
7     163   72
8     152   62
9     131   48


In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,1].values
print(x)
print(y)

[[151]
 [174]
 [138]
 [186]
 [128]
 [136]
 [179]
 [163]
 [152]
 [131]]
[63 81 56 91 47 57 76 72 62 48]


In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)
print("Accuracy:",regressor.score(x,y)*100)

Accuracy: 95.47822477500306


In [ ]:
regressor.predict([[180]])

array([82.97479377])